version: '3.2'

services:
  db:
    container_name: nanu_db
    restart: 'no'
    image: postgres:14.2
    environment:
      POSTGRES_DB: nanu
      POSTGRES_USER: nanu
      POSTGRES_PASSWORD: development_only
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: nanu_redis
    restart: 'no'
    image: bitnami/redis:6.2.5
    environment:
      REDIS_PASSWORD: development_only
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/bitnami/redis/data

  backend:
    container_name: nanu_backend
    restart: 'no'
    build:
      context: ./backend
      dockerfile: 'Dockerfile'
      target: dev
    volumes:
      - type: bind
        source: ./backend
        target: /app
        consistency: cached
    environment:
      NANU_DB_HOST: db
      NANU_DB_PORT: 5432
      NANU_DB_USER: nanu
      NANU_DB_PASS: development_only
      NANU_DB_BASE: nanu
      NANU_REDIS_HOST: redis
      NANU_REDIS_PORT: 6379
      NANU_REDIS_PASSWORD: development_only
      NANU_RELOAD: true
      APP_ENVIRONMENT: dev
    ports:
      - '8000:8000' # Application port
      - '5678:5678' # Debugger port
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redis_data:
